"""
core/god_roster_data.py — bundled god-roster snapshot (GENERATED).

Fallback data for core/god_roster.py when data/god_roster.json does
not exist yet and the live wiki fetch fails. Regenerate with:

    python tools/update_bundled_roster.py

Snapshot taken 2026-07-04 from wiki.smite2.com (SMITE 2, 88 gods)
and smite.fandom.com (SMITE 1 catalog, 130 gods).
"""

BUNDLED_SNAPSHOT_DATE = "2026-07-04"

# SMITE 2 released roster: [name, slug, wiki icon filename, first_seen]
# first_seen is None for gods that predate roster tracking.
BUNDLED_S2_GODS = [
    ("Achilles", "achilles", "T_Achilles(S2)_Default_Icon.png", None),
    ("Agni", "agni", "T_Agni(S2)_Default_Icon.png", None),
    ("Ah Puch", "ah-puch", "T_Ah_Puch(S2)_Default_Icon.png", "2026-07-04"),
    ("Aladdin", "aladdin", "T_Aladdin(S2)_Default_Icon.png", None),
    ("Amaterasu", "amaterasu", "T_Amaterasu(S2)_Default_Icon.png", None),
    ("Anhur", "anhur", "T_Anhur(S2)_Default_Icon.png", None),
    ("Anubis", "anubis", "T_Anubis(S2)_Default_Icon.png", None),
    ("Aphrodite", "aphrodite", "T_Aphrodite(S2)_Default_Icon.png", None),
    ("Apollo", "apollo", "T_Apollo(S2)_Default_Icon.png", None),
    ("Ares", "ares", "T_Ares(S2)_Default_Icon.png", None),
    ("Artemis", "artemis", "T_Artemis(S2)_Default_Icon.png", None),
    ("Artio", "artio", "T_Artio(S2)_Default_Icon.png", None),
    ("Athena", "athena", "T_Athena(S2)_Default_Icon.png", None),
    ("Atlas", "atlas", "T_Atlas(S2)_Default_Icon.png", None),
    ("Awilix", "awilix", "T_Awilix(S2)_Default_Icon.png", None),
    ("Bacchus", "bacchus", "T_Bacchus(S2)_Default_Icon.png", None),
    ("Baron Samedi", "baron-samedi", "T_Baron_Samedi(S2)_Default_Icon.png", None),
    ("Bastet", "bastet", "T_Bastet(S2)_Default_Icon.png", "2026-07-04"),
    ("Bellona", "bellona", "T_Bellona(S2)_Default_Icon.png", None),
    ("Cabrakan", "cabrakan", "T_Cabrakan(S2)_Default_Icon.png", None),
    ("Cerberus", "cerberus", "T_Cerberus(S2)_Default_Icon.png", None),
    ("Cernunnos", "cernunnos", "T_Cernunnos(S2)_Default_Icon.png", None),
    ("Chaac", "chaac", "T_Chaac(S2)_Default_Icon.png", None),
    ("Charon", "charon", "T_Charon(S2)_Default_Icon.png", None),
    ("Chiron", "chiron", "T_Chiron(S2)_Default_Icon.png", None),
    ("Chronos", "chronos", "T_Chronos(S2)_Default_Icon.png", "2026-07-04"),
    ("Cu Chulainn", "cu-chulainn", "T_CuChulainn_Default_Icon.png", "2026-07-04"),
    ("Cupid", "cupid", "T_Cupid(S2)_Default_Icon.png", None),
    ("Da Ji", "da-ji", "T_DaJi(S2)_Default_Icon.png", None),
    ("Danzaburou", "danzaburou", "T_Danzaburou(S2)_Default_Icon.png", None),
    ("Discordia", "discordia", "T_Discordia(S2)_Default_Icon.png", None),
    ("Eset", "eset", "T_Eset(S2)_Default_Icon.png", None),
    ("Fenrir", "fenrir", "T_Fenrir(S2)_Default_Icon.png", None),
    ("Ganesha", "ganesha", "T_Ganesha_Default_Icon.png", None),
    ("Geb", "geb", "T_Geb(S2)_Default_Icon.png", None),
    ("Gilgamesh", "gilgamesh", "T_Gilgamesh(S2)_Default_Icon.png", None),
    ("Guan Yu", "guan-yu", "T_Guan_Yu(S2)_Default_Icon.png", None),
    ("Hades", "hades", "T_Hades(S2)_Default_Icon.png", None),
    ("Hecate", "hecate", "T_Hecate(S2)_Default_Icon.png", None),
    ("Hercules", "hercules", "T_Hercules(S2)_Default_Icon.png", None),
    ("Horus", "horus", "T_Horus(S2)_Default_Icon.png", "2026-07-04"),
    ("Hou Yi", "hou-yi", "T_Hou_Yi(S2)_Default_Icon.png", None),
    ("Hua Mulan", "hua-mulan", "T_Hua_Mulan(S2)_Default_Icon.png", None),
    ("Hun Batz", "hun-batz", "T_Hun_Batz(S2)_Default_Icon.png", None),
    ("Ishtar", "ishtar", "T_Ishtar(S2)_Default_Icon.png", None),
    ("Izanami", "izanami", "T_Izanami(S2)_Default_Icon.png", None),
    ("Janus", "janus", "T_Janus(S2)_Default_Icon.png", None),
    ("Jing Wei", "jing-wei", "T_JingWei(S2)_Default_Icon.png", None),
    ("Jormungandr", "jormungandr", "T_Jormungandr(S2)_Default_Icon.png", None),
    ("Kali", "kali", "T_Kali(S2)_Default_Icon.png", None),
    ("Khepri", "khepri", "T_Khepri(S2)_Default_Icon.png", None),
    ("Kukulkan", "kukulkan", "T_Kukulkan(S2)_Default_Icon.png", None),
    ("Loki", "loki", "T_Loki(S2)_Default_Icon.png", None),
    ("Medusa", "medusa", "T_Medusa(S2)_Default_Icon.png", None),
    ("Mercury", "mercury", "T_Mercury_Default_Icon.png", None),
    ("Merlin", "merlin", "T_Merlin(S2)_Default_Icon.png", None),
    ("Mordred", "mordred", "T_Mordred(S2)_Default_Icon.png", None),
    ("Morgan Le Fay", "morgan-le-fay", "T_MorganLeFay(S2)_Default_Icon.png", None),
    ("Ne Zha", "ne-zha", "T_NeZha(S2)_Default_Icon.png", None),
    ("Neith", "neith", "T_Neith(S2)_Default_Icon.png", None),
    ("Nemesis", "nemesis", "T_Nemesis(S2)_Default_Icon.png", None),
    ("Nu Wa", "nu-wa", "T_Nu_Wa(S2)_Default_Icon.png", None),
    ("Nut", "nut", "T_Nut(S2)_Default_Icon.png", None),
    ("Odin", "odin", "T_Odin(S2)_Default_Icon.png", None),
    ("Osiris", "osiris", "T_Osiris(S2)_Default_Icon.png", None),
    ("Pele", "pele", "T_Pele(S2)_Default_Icon.png", None),
    ("Poseidon", "poseidon", "T_Poseidon(S2)_Default_Icon.png", None),
    ("Princess Bari", "princess-bari", "T_Princess_Bari(S2)_Default_Icon.png", None),
    ("Ra", "ra", "T_Ra(S2)_Default_Icon.png", None),
    ("Rama", "rama", "T_Rama(S2)_Default_Icon.png", None),
    ("Ratatoskr", "ratatoskr", "T_Ratatoskr(S2)_Default_Icon.png", None),
    ("Scylla", "scylla", "T_Scylla_Default_Icon.png", None),
    ("Sobek", "sobek", "T_Sobek(S2)_Default_Icon.png", None),
    ("Sol", "sol", "T_Sol(S2)_Default_Icon.png", None),
    ("Sun Wukong", "sun-wukong", "T_Sun_Wukong(S2)_Default_Icon.png", None),
    ("Susano", "susano", "T_Susano(S2)_Default_Icon.png", None),
    ("Sylvanus", "sylvanus", "T_Sylvanus(S2)_Default_Icon.png", None),
    ("Thanatos", "thanatos", "T_Thanatos(S2)_Default_Icon.png", None),
    ("The Morrigan", "the-morrigan", "T_The_Morrigan(S2)_Default_Icon.png", None),
    ("Thor", "thor", "T_Thor(S2)_Default_Icon.png", None),
    ("Tsukuyomi", "tsukuyomi", "T_Tsukuyomi(S2)_Default_Icon.png", None),
    ("Ullr", "ullr", "T_Ullr(S2)_Default_Icon.png", None),
    ("Vulcan", "vulcan", "T_Vulcan(S2)_Default_Icon.png", None),
    ("Xbalanque", "xbalanque", "T_Xbalanque(S2)_Default_Icon.png", None),
    ("Xing Tian", "xing-tian", "T_XingTian_Default_Icon.png", "2026-07-04"),
    ("Yemoja", "yemoja", "T_Yemoja(S2)_Default_Icon.png", None),
    ("Ymir", "ymir", "T_Ymir(S2)_Default_Icon.png", None),
    ("Zeus", "zeus", "T_Zeus(S2)_Default_Icon.png", None),
]

# Full SMITE 1 catalog: [name, slug, fandom-wiki icon filename].
# SMITE 1 is frozen (no new gods), so this list is static. Used to
# recognize not-yet-ported god names in chat and to fetch fallback
# display art for gods that join SMITE 2 later.
SMITE1_CATALOG = [
    ("Achilles", "achilles", "T_Achilles_Default_Icon.png"),
    ("Agni", "agni", "T_Agni_Default_Icon.png"),
    ("Ah Muzen Cab", "ah-muzen-cab", "T_AMC_Default_Icon.png"),
    ("Ah Puch", "ah-puch", "T_AhPuch_Default_Icon.png"),
    ("Amaterasu", "amaterasu", "T_Amaterasu_Default_Icon.png"),
    ("Anhur", "anhur", "T_Anhur_Default_Icon.png"),
    ("Anubis", "anubis", "T_Anubis_Default_Icon.png"),
    ("Ao Kuang", "ao-kuang", "T_AoKuang_Default_Icon.png"),
    ("Aphrodite", "aphrodite", "T_Aphrodite_Default_Icon.png"),
    ("Apollo", "apollo", "T_Apollo_Default_Icon.png"),
    ("Arachne", "arachne", "T_Arachne_Default_Icon.png"),
    ("Ares", "ares", "T_Ares_Default_Icon.png"),
    ("Artemis", "artemis", "T_Artemis_Default_Icon.png"),
    ("Artio", "artio", "T_Artio_Default_Icon.png"),
    ("Athena", "athena", "T_Athena_Default_Icon.png"),
    ("Atlas", "atlas", "T_Atlas_Default_Icon.png"),
    ("Awilix", "awilix", "T_Awilix_Default_Icon.png"),
    ("Baba Yaga", "baba-yaga", "T_BabaYaga_Default_Icon.png"),
    ("Bacchus", "bacchus", "T_Bacchus_Default_Icon.png"),
    ("Bakasura", "bakasura", "T_Bakasura_Default_Icon.png"),
    ("Bake Kujira", "bake-kujira", "T_BakeKujira_Default_Icon.png"),
    ("Baron Samedi", "baron-samedi", "T_BaronSamedi_Default_Icon.png"),
    ("Bastet", "bastet", "T_Bastet_Default_Icon.png"),
    ("Bellona", "bellona", "T_Bellona_Default_Icon.png"),
    ("Cabrakan", "cabrakan", "T_Cabrakan_Default_Icon.png"),
    ("Camazotz", "camazotz", "T_Camazotz_Default_Icon.png"),
    ("Cerberus", "cerberus", "T_Cerberus_Default_Icon.png"),
    ("Cernunnos", "cernunnos", "T_Cernunnos_Default_Icon.png"),
    ("Chaac", "chaac", "T_Chaac_Default_Icon.png"),
    ("Chang'e", "change", "T_ChangE_Default_Icon.png"),
    ("Charon", "charon", "T_Charon_Default_Icon.png"),
    ("Charybdis", "charybdis", "T_Charybdis_Default_Icon.png"),
    ("Chernobog", "chernobog", "T_Chernobog_Default_Icon.png"),
    ("Chiron", "chiron", "T_Chiron_Default_Icon.png"),
    ("Chronos", "chronos", "T_Chronos_Default_Icon.png"),
    ("Cliodhna", "cliodhna", "T_Cliodhna_Default_Icon.png"),
    ("Cthulhu", "cthulhu", "T_Cthulhu_Default_Icon.png"),
    ("Cu Chulainn", "cu-chulainn", "T_CuChulainn_Default_Icon.png"),
    ("Cupid", "cupid", "T_Cupid_Default_Icon.png"),
    ("Da Ji", "da-ji", "T_DaJi_Default_Icon.png"),
    ("Danzaburou", "danzaburou", "T_Danzaburou_Default_Icon.png"),
    ("Discordia", "discordia", "T_Discordia_Default_Icon.png"),
    ("Erlang Shen", "erlang-shen", "T_ErLangShen_Default_Icon.png"),
    ("Eset", "eset", "T_Eset_Default_Icon.png"),
    ("Fafnir", "fafnir", "T_Fafnir_Default_Icon.png"),
    ("Fenrir", "fenrir", "T_Fenrir_Default_Icon.png"),
    ("Freya", "freya", "T_Freya_Default_Icon.png"),
    ("Ganesha", "ganesha", "T_Ganesha_Default_Icon.png"),
    ("Geb", "geb", "T_Geb_Default_Icon.png"),
    ("Gilgamesh", "gilgamesh", "T_Gilgamesh_Default_Icon.png"),
    ("Guan Yu", "guan-yu", "T_GuanYu_Default_Icon.png"),
    ("Hachiman", "hachiman", "T_Hachiman_Default_Icon.png"),
    ("Hades", "hades", "T_Hades_Default_Icon.png"),
    ("He Bo", "he-bo", "T_HeBo_Default_Icon.png"),
    ("Heimdallr", "heimdallr", "T_Heimdallr_Default_Icon.png"),
    ("Hel", "hel", "T_Hel_Default_Icon.png"),
    ("Hera", "hera", "T_Hera_Default_Icon.png"),
    ("Hercules", "hercules", "T_Hercules_Default_Icon.png"),
    ("Horus", "horus", "T_Horus_Default_Icon.png"),
    ("Hou Yi", "hou-yi", "T_HouYi_Default_Icon.png"),
    ("Hun Batz", "hun-batz", "T_HunBatz_Default_Icon.png"),
    ("Ishtar", "ishtar", "T_Ishtar_Default_Icon.png"),
    ("Ix Chel", "ix-chel", "T_IxChel_Default_Icon.png"),
    ("Izanami", "izanami", "T_Izanami_Default_Icon.png"),
    ("Janus", "janus", "T_Janus_Default_Icon.png"),
    ("Jing Wei", "jing-wei", "T_JingWei_Default_Icon.png"),
    ("Jormungandr", "jormungandr", "T_Jormungandr_Default_Icon.png"),
    ("Kali", "kali", "T_Kali_Default_Icon.png"),
    ("Khepri", "khepri", "T_Khepri_Default_Icon.png"),
    ("King Arthur", "king-arthur", "T_KingArthur_Default_Icon.png"),
    ("Kukulkan", "kukulkan", "T_Kukulkan_Default_Icon.png"),
    ("Kumbhakarna", "kumbhakarna", "T_Kumbhakarna_Default_Icon.png"),
    ("Kuzenbo", "kuzenbo", "T_Kuzenbo_Default_Icon.png"),
    ("Lancelot", "lancelot", "T_Lancelot_Default_Icon.png"),
    ("Loki", "loki", "T_Loki_Default_Icon.png"),
    ("Maman Brigitte", "maman-brigitte", "T_MamanBrigitte_Default_Icon.png"),
    ("Martichoras", "martichoras", "T_Martichoras_Default_Icon.png"),
    ("Maui", "maui", "T_Maui_Default_Icon.png"),
    ("Medusa", "medusa", "T_Medusa_Default_Icon.png"),
    ("Mercury", "mercury", "T_Mercury_Default_Icon.png"),
    ("Merlin", "merlin", "T_Merlin_Default_Icon.png"),
    ("Morgan Le Fay", "morgan-le-fay", "T_MorganLeFay_Default_Icon.png"),
    ("Mulan", "mulan", "T_Mulan_Default_Icon.png"),
    ("Ne Zha", "ne-zha", "T_NeZha_Default_Icon.png"),
    ("Neith", "neith", "T_Neith_Default_Icon.png"),
    ("Nemesis", "nemesis", "T_Nemesis_Default_Icon.png"),
    ("Nike", "nike", "T_Nike_Default_Icon.png"),
    ("Nox", "nox", "T_Nox_Default_Icon.png"),
    ("Nu Wa", "nu-wa", "T_NuWa_Default_Icon.png"),
    ("Nut", "nut", "T_Nut_Default_Icon.png"),
    ("Odin", "odin", "T_Odin_Default_Icon.png"),
    ("Olorun", "olorun", "T_Olorun_Default_Icon.png"),
    ("Osiris", "osiris", "T_Osiris_Default_Icon.png"),
    ("Pele", "pele", "T_Pele_Default_Icon.png"),
    ("Persephone", "persephone", "T_Persephone_Default_Icon.png"),
    ("Poseidon", "poseidon", "T_Poseidon_Default_Icon.png"),
    ("Ra", "ra", "T_Ra_Default_Icon.png"),
    ("Raijin", "raijin", "T_Raijin_Default_Icon.png"),
    ("Rama", "rama", "T_Ram_Default_Icon.png"),
    ("Ratatoskr", "ratatoskr", "T_Ratatoskr_Default_Icon.png"),
    ("Ravana", "ravana", "T_Ravana_Default_Icon.png"),
    ("Scylla", "scylla", "T_Scylla_Default_Icon.png"),
    ("Serqet", "serqet", "T_Serqet_Default_Icon.png"),
    ("Set", "set", "T_Set_Default_Icon.png"),
    ("Shiva", "shiva", "T_Shiva_Default_Icon.png"),
    ("Skadi", "skadi", "T_Skadi_Default_Icon.png"),
    ("Sobek", "sobek", "T_Sobek_Default_Icon.png"),
    ("Sol", "sol", "T_Sol_Default_Icon.png"),
    ("Sun Wukong", "sun-wukong", "T_SunWukong_Default_Icon.png"),
    ("Surtr", "surtr", "T_Surtr_Default_Icon.png"),
    ("Susano", "susano", "T_Susano_Default_Icon.png"),
    ("Sylvanus", "sylvanus", "T_Sylvanus_Default_Icon.png"),
    ("Terra", "terra", "T_Terra_Default_Icon.png"),
    ("Thanatos", "thanatos", "T_Thanatos_Default_Icon.png"),
    ("The Morrigan", "the-morrigan", "T_TheMorrigan_Default_Icon.png"),
    ("Thor", "thor", "T_Thor_Default_Icon.png"),
    ("Thoth", "thoth", "T_Thoth_Default_Icon.png"),
    ("Tiamat", "tiamat", "T_Tiamat_Default_Icon.png"),
    ("Tsukuyomi", "tsukuyomi", "T_Tsukuyomi_Default_Icon.png"),
    ("Tyr", "tyr", "T_Tyr_Default_Icon.png"),
    ("Ullr", "ullr", "T_Ullr_Default_Icon.png"),
    ("Vamana", "vamana", "T_Vamana_Default_Icon.png"),
    ("Vulcan", "vulcan", "T_Vulcan_Default_Icon.png"),
    ("Xbalanque", "xbalanque", "T_Xbalanque_Default_Icon.png"),
    ("Xing Tian", "xing-tian", "T_XingTian_Default_Icon.png"),
    ("Yemoja", "yemoja", "T_Yemoja_Default_Icon.png"),
    ("Ymir", "ymir", "T_Ymir_Default_Icon.png"),
    ("Yu Huang", "yu-huang", "T_YuHuang_Default_Icon.png"),
    ("Zeus", "zeus", "T_Zeus_Default_Icon.png"),
    ("Zhong Kui", "zhong-kui", "T_ZhongKui_Default_Icon.png"),
]
