r"""
tools/gen_readme_sources.py — rewrite README's "OBS browser sources" list
from core/sources.py (the registry the dashboard /sources page uses), so
the two never drift again.

    python tools\gen_readme_sources.py          # rewrite README.md in place
    python tools\gen_readme_sources.py --check  # exit 1 if README is stale

The block between the markers below is replaced; everything else in the
README is left alone.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from core.sources import readme_lines  # noqa: E402

README = REPO_ROOT / "README.md"
START = "<!-- sources:start (generated by tools/gen_readme_sources.py) -->"
END = "<!-- sources:end -->"


def render() -> str:
    return START + "\n" + "\n".join(readme_lines()) + "\n" + END


def main() -> int:
    check = "--check" in sys.argv
    text = README.read_text(encoding="utf-8")
    block = render()
    if START in text and END in text:
        a = text.index(START)
        b = text.index(END) + len(END)
        new = text[:a] + block + text[b:]
    else:
        # first run: replace the hand-written bullet list under "### 6. OBS browser sources"
        head = "### 6. OBS browser sources"
        if head not in text:
            print("README has no OBS browser sources section", file=sys.stderr)
            return 2
        a = text.index(head)
        intro_end = text.index("\n- ", a)
        b = text.index("\n\n", intro_end)
        new = text[:intro_end + 1] + block + text[b:]
    if new == text:
        print("README sources list is up to date")
        return 0
    if check:
        print("README sources list is stale: run tools/gen_readme_sources.py", file=sys.stderr)
        return 1
    README.write_text(new, encoding="utf-8")
    print("README sources list rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
