#!/usr/bin/env python3
"""
migrate_recordings.py
=====================

One-shot move of the recordings library from ``C:\\Projects\\HatmasBot\\recordings``
to ``D:\\Recordings`` (config.RECORDINGS_DIR), done 2026-09-15. Kept in the
repo as the record of what happened and so it can be re-run if it stops
partway: every step is idempotent (already-moved files are skipped,
already-deleted junk is ignored).

Steps, in order:

  1. preflight   nothing recording right now, bot not holding the VOD
                 index open, enough free space on D:.
  2. lift        D:\\Recordings\\Palworld\\* -> D:\\Recordings\\ (same volume,
                 instant rename). OBS recorded there from 7/19 to 9/15.
  3. junk        delete Vegas .sfk peak files, .tiktok_bg render folders,
                 _rescan_diff.json reports, OBS false starts (<1 MB or
                 shorter than 10 s).
  4. sidecars    delete every .events.json under the C: tree; they get
                 regenerated by ``process_recordings.py --reprocess-all``.
  5. replays     OBS replay-buffer clips whose time window sits entirely
                 inside a full recording are duplicates: report them to
                 data/vod/replay_overlap_report.json and delete them.
  6. copy        robocopy C: -> D: preserving timestamps, then verify every
                 source file has a same-size counterpart, THEN delete the
                 C: tree. Nothing on C: is removed before the verify passes.
  7. index       drop every hatmaster row from data/vod/vod_index.db
                 (transcripts are being redone overnight) and empty the
                 clip cache. Other-channel rows and the vods table stay.
  8. print the overnight commands.

Dry run is the default and touches nothing. ``--execute`` does the work.
Everything is logged to data/migrate_recordings.log.

    python tools\\migrate_recordings.py              # dry run
    python tools\\migrate_recordings.py --execute
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from core import config  # noqa: E402

OLD_ROOT = _REPO_ROOT / "recordings"
NEW_ROOT = Path(config.RECORDINGS_DIR)
PALWORLD = NEW_ROOT / "Palworld"
CHANNELS = Path(config.VOD_CHANNELS_ROOT)
DB_PATH = Path(config.VOD_DB_PATH)
CLIPS_DIR = Path(config.VOD_CLIPS_DIR)
LOG_PATH = config.DATA_DIR / "migrate_recordings.log"
REPORT_PATH = config.DATA_DIR / "vod" / "replay_overlap_report.json"

EMPTY_MP4_BYTES = 1_000_000          # OBS false starts are 0 bytes; anything under 1 MB is not a recording
MIN_RECORDING_S = 10                 # start/stop false starts; James: anything under 10 s is junk
FREE_MARGIN_GB = 30                  # keep at least this much free on D: after the copy
RECENT_WRITE_S = 90                  # an mp4 touched this recently means OBS is still writing
REPLAY_SLACK_S = 10                  # timestamp tolerance for "replay inside recording"
TS_RE = re.compile(r"(\d{4}-\d{2}-\d{2})[_ ](\d{2}-\d{2}-\d{2})")

_log_fh = None
_durations: dict[Path, float] = {}   # ffprobe cache shared by the junk and replay steps


def log(msg: str = "") -> None:
    print(msg)
    if _log_fh:
        _log_fh.write(msg + "\n")
        _log_fh.flush()


def gb(n: int | float) -> str:
    return f"{n / 1e9:,.1f} GB"


def mp4s_under(root: Path, recursive: bool, skip: set[str] = frozenset()) -> list[Path]:
    if not root.is_dir():
        return []
    it = root.rglob("*.mp4") if recursive else root.glob("*.mp4")
    out = []
    for p in it:
        if not p.is_file():
            continue
        rel = p.relative_to(root).parts[:-1]
        if any(part.lower() in skip or part.startswith((".", "_")) for part in rel):
            continue
        out.append(p)
    return sorted(out)


def ffprobe_duration(p: Path) -> float:
    if p in _durations:
        return _durations[p]
    try:
        out = subprocess.run(
            [config.VOD_FFPROBE, "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", str(p)],
            capture_output=True, text=True, timeout=120,
        ).stdout.strip()
        d = float(out)
    except (ValueError, subprocess.SubprocessError, OSError):
        d = 0.0
    _durations[p] = d
    return d


def all_mp4s() -> list[Path]:
    return (mp4s_under(OLD_ROOT, True, {"channels"})
            + mp4s_under(NEW_ROOT, False)
            + mp4s_under(PALWORLD, False))      # still there on a dry run


# ── 1. preflight ────────────────────────────────────────────────────────────

def preflight(execute: bool) -> bool:
    ok = True
    log("== 1. preflight ==")
    if not OLD_ROOT.is_dir() and not PALWORLD.is_dir():
        log(f"   nothing to migrate: {OLD_ROOT} and {PALWORLD} are both gone")
    if not NEW_ROOT.is_dir():
        log(f"   FAIL: {NEW_ROOT} does not exist")
        ok = False

    now = time.time()
    fresh = [p for root in (OLD_ROOT, NEW_ROOT, PALWORLD)
             for p in mp4s_under(root, recursive=False)
             if now - p.stat().st_mtime < RECENT_WRITE_S]
    if fresh:
        log(f"   FAIL: OBS looks like it is still writing: {', '.join(p.name for p in fresh)}")
        ok = False
    else:
        log("   no recording in progress")

    if DB_PATH.exists():
        try:
            os.replace(DB_PATH, DB_PATH)        # fails while another process holds it open
            log("   VOD index not held open by the bot")
        except OSError as e:
            log(f"   FAIL: {DB_PATH.name} is open by another process (bot running?): {e}")
            ok = False

    to_copy = sum(p.stat().st_size for p in OLD_ROOT.rglob("*") if p.is_file()) if OLD_ROOT.is_dir() else 0
    free = shutil.disk_usage(NEW_ROOT).free if NEW_ROOT.is_dir() else 0
    log(f"   C: tree {gb(to_copy)}, D: free {gb(free)}, "
        f"free after copy {gb(free - to_copy)} (margin {FREE_MARGIN_GB} GB)")
    if free - to_copy < FREE_MARGIN_GB * 1e9:
        log("   FAIL: not enough free space on D:")
        ok = False
    return ok


# ── 2. lift Palworld ────────────────────────────────────────────────────────

def lift_palworld(execute: bool) -> bool:
    log("== 2. lift D:\\Recordings\\Palworld -> D:\\Recordings ==")
    if not PALWORLD.is_dir():
        log("   already done (folder gone)")
        return True
    files = sorted(p for p in PALWORLD.iterdir() if p.is_file())
    clashes = [p.name for p in files if (NEW_ROOT / p.name).exists()]
    if clashes:
        log(f"   FAIL: {len(clashes)} name(s) already exist in {NEW_ROOT}: {clashes[:5]}")
        return False
    log(f"   {len(files)} files, {gb(sum(p.stat().st_size for p in files))}")
    junk_dirs = [p for p in PALWORLD.iterdir() if p.is_dir() and p.name == ".tiktok_bg"]
    if execute:
        for p in files:
            os.replace(p, NEW_ROOT / p.name)
        for d in junk_dirs:
            shutil.rmtree(d)
        leftovers = list(PALWORLD.iterdir())
        if leftovers:
            log(f"   left behind (not files): {[p.name for p in leftovers]}")
        else:
            PALWORLD.rmdir()
            log("   moved, folder removed")
    return True


# ── 3. junk ─────────────────────────────────────────────────────────────────

def sweep_junk(execute: bool) -> None:
    log("== 3. junk ==")
    files: list[Path] = []
    dirs: list[Path] = []
    for root in (OLD_ROOT, NEW_ROOT):
        if not root.is_dir():
            continue
        for p in root.rglob("*"):
            if CHANNELS in p.parents or p == CHANNELS:
                continue
            if p.is_dir() and p.name == ".tiktok_bg":
                dirs.append(p)
            elif p.is_file():
                if p.suffix.lower().startswith(".sfk"):
                    files.append(p)
                elif p.name == "_rescan_diff.json":
                    files.append(p)
                elif p.suffix.lower() == ".mp4" and p.stat().st_size < EMPTY_MP4_BYTES:
                    files.append(p)
    files = [f for f in files if not any(d in f.parents for d in dirs)]
    vids = [v for v in all_mp4s() if v not in files]
    with ThreadPoolExecutor(8) as ex:
        list(ex.map(ffprobe_duration, vids))
    shorts = [v for v in vids if ffprobe_duration(v) < MIN_RECORDING_S]
    files += shorts
    sfk = [f for f in files if f.suffix.lower().startswith(".sfk")]
    empties = [f for f in files if f.suffix.lower() == ".mp4" and f.stat().st_size < EMPTY_MP4_BYTES]
    reports = [f for f in files if f.name == "_rescan_diff.json"]
    log(f"   {len(sfk)} Vegas .sfk peak files ({gb(sum(f.stat().st_size for f in sfk))})")
    log(f"   {len(dirs)} .tiktok_bg folders: {[str(d.relative_to(d.parents[1])) for d in dirs]}")
    log(f"   {len(reports)} _rescan_diff.json: {[str(f) for f in reports]}")
    log(f"   {len(empties)} empty recordings: {[(f.name, f.stat().st_size) for f in empties]}")
    log(f"   {len(shorts)} recordings under {MIN_RECORDING_S} s ({gb(sum(f.stat().st_size for f in shorts))}):")
    for f in shorts:
        log(f"     {f.name}  {ffprobe_duration(f):.1f} s  {f.stat().st_size / 1e6:.0f} MB")
    if execute:
        for f in files:
            f.unlink()
        for d in dirs:
            shutil.rmtree(d)
        log("   deleted")


# ── 4. sidecars ─────────────────────────────────────────────────────────────

def drop_sidecars(execute: bool) -> None:
    log("== 4. .events.json sidecars (regenerated by the overnight rescan) ==")
    found = [p for root in (OLD_ROOT, NEW_ROOT) if root.is_dir()
             for p in root.rglob("*.events.json")
             if CHANNELS not in p.parents]
    log(f"   {len(found)} sidecars")
    if execute:
        for p in found:
            p.unlink()
        log("   deleted")


# ── 5. duplicate replays ────────────────────────────────────────────────────

def _stamp(p: Path) -> datetime | None:
    m = TS_RE.search(p.name)
    if not m:
        return None
    return datetime.strptime(f"{m.group(1)} {m.group(2)}", "%Y-%m-%d %H-%M-%S")


def replay_overlaps(execute: bool) -> None:
    """A replay-buffer clip is named by the moment it was saved and runs
    backwards from there; a full recording is named by its start. Sorted
    recordings lost their timestamp name, so their end = mtime."""
    log("== 5. replay clips that duplicate a full recording ==")
    everything = all_mp4s()
    with ThreadPoolExecutor(8) as ex:
        durs = dict(zip(everything, ex.map(ffprobe_duration, everything)))
    fulls: list[tuple[Path, datetime, datetime]] = []
    replays: list[tuple[Path, datetime, datetime]] = []
    for p in everything:
        d = durs[p]
        if d <= 0:
            continue
        stamp = _stamp(p)
        if "replay" in p.name.lower():
            if stamp:
                replays.append((p, stamp - timedelta(seconds=d), stamp))
            continue
        if stamp:
            fulls.append((p, stamp, stamp + timedelta(seconds=d)))
        else:
            end = datetime.fromtimestamp(p.stat().st_mtime)
            fulls.append((p, end - timedelta(seconds=d), end))
    slack = timedelta(seconds=REPLAY_SLACK_S)
    dups = []
    for p, s, e in replays:
        hit = next((f for f in fulls if f[1] - slack <= s and e <= f[2] + slack), None)
        if hit:
            dups.append({"replay": str(p), "inside": str(hit[0]),
                         "replay_window": [s.isoformat(), e.isoformat()],
                         "size_bytes": p.stat().st_size})
    log(f"   {len(replays)} replay clips checked against {len(fulls)} full recordings")
    log(f"   {len(dups)} duplicates ({gb(sum(d['size_bytes'] for d in dups))}):")
    for d in dups:
        log(f"     {Path(d['replay']).name}  inside  {Path(d['inside']).name}")
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(json.dumps({
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "deleted": execute, "duplicates": dups,
    }, indent=2), encoding="utf-8")
    log(f"   report: {REPORT_PATH}")
    if execute:
        for d in dups:
            Path(d["replay"]).unlink()
        log("   deleted")


# ── 6. copy + verify + delete ───────────────────────────────────────────────

def copy_and_verify(execute: bool) -> bool:
    log("== 6. copy C: tree -> D: ==")
    if not OLD_ROOT.is_dir():
        log("   already done (C: tree gone)")
        return True
    src_files = [p for p in OLD_ROOT.rglob("*") if p.is_file()]
    clashes = [p for p in src_files
               if (NEW_ROOT / p.relative_to(OLD_ROOT)).exists()
               and (NEW_ROOT / p.relative_to(OLD_ROOT)).stat().st_size != p.stat().st_size]
    if clashes:
        log(f"   FAIL: {len(clashes)} destination file(s) exist with a different size: "
            f"{[str(p.relative_to(OLD_ROOT)) for p in clashes[:5]]}")
        return False
    log(f"   {len(src_files)} files, {gb(sum(p.stat().st_size for p in src_files))}, "
        f"{sum(1 for p in OLD_ROOT.iterdir() if p.is_dir())} folders")
    if not execute:
        return True

    cmd = ["robocopy", str(OLD_ROOT), str(NEW_ROOT), "/E", "/COPY:DAT", "/DCOPY:T",
           "/R:2", "/W:5", "/NP", "/NFL", "/NDL", "/NJH"]
    log("   " + " ".join(cmd))
    t0 = time.time()
    rc = subprocess.run(cmd, stdout=_log_fh or None, stderr=subprocess.STDOUT).returncode
    log(f"   robocopy exit {rc} after {time.time() - t0:.0f}s")
    if rc >= 8:
        log("   FAIL: robocopy reported errors; C: tree left in place")
        return False

    bad = []
    for p in src_files:
        q = NEW_ROOT / p.relative_to(OLD_ROOT)
        if not q.is_file() or q.stat().st_size != p.stat().st_size:
            bad.append(p)
    if bad:
        log(f"   FAIL: {len(bad)} file(s) missing or size mismatch on D:; C: tree left in place: "
            f"{[str(p.relative_to(OLD_ROOT)) for p in bad[:5]]}")
        return False
    log(f"   verified {len(src_files)} files byte-count match on D:")
    shutil.rmtree(OLD_ROOT)
    log(f"   deleted {OLD_ROOT}")
    return True


# ── 7. index reset ──────────────────────────────────────────────────────────

def reset_index(execute: bool) -> None:
    log("== 7. VOD index: drop hatmaster rows, empty clip cache ==")
    if not DB_PATH.exists():
        log("   no index database")
        return
    from vodsearch.store import Store
    store = Store(DB_PATH)
    rows = store.conn.execute(
        "SELECT id, channel FROM recordings").fetchall()
    mine = [r[0] for r in rows if r[1] == "hatmaster"]
    log(f"   {len(mine)} hatmaster recordings to drop, {len(rows) - len(mine)} other-channel rows kept")
    clips = [p for p in CLIPS_DIR.glob("*") if p.is_file()] if CLIPS_DIR.is_dir() else []
    log(f"   {len(clips)} cached clips ({gb(sum(p.stat().st_size for p in clips))})")
    if execute:
        for rid in mine:
            store.delete_recording(rid)
        store.conn.execute("VACUUM")
        store.conn.commit()
        for p in clips:
            p.unlink()
        log("   done")
    store.conn.close()


def print_followups() -> None:
    py = sys.executable
    log("== 8. overnight (run from the repo root, GPU idle) ==")
    log(f'   "{py}" tools\\process_recordings.py --reprocess-all')
    log(f'   "{py}" tools\\vod_index.py index')
    log("   (the sorter files every loose recording and rewrites every sidecar, ~3.5 h;")
    log("    the indexer then transcribes everything, ~4.5 h)")


def main() -> int:
    global _log_fh
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[1],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--execute", action="store_true", help="actually do it (default: dry run)")
    args = ap.parse_args()
    execute = args.execute

    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    _log_fh = LOG_PATH.open("a", encoding="utf-8")
    log(f"\n===== migrate_recordings {'EXECUTE' if execute else 'DRY RUN'} "
        f"{datetime.now().isoformat(timespec='seconds')} =====")
    log(f"old root: {OLD_ROOT}\nnew root: {NEW_ROOT}")

    if not preflight(execute):
        log("preflight failed; nothing changed")
        return 2
    if not lift_palworld(execute):
        return 2
    sweep_junk(execute)
    drop_sidecars(execute)
    replay_overlaps(execute)
    if not copy_and_verify(execute):
        return 2
    reset_index(execute)
    print_followups()
    log("===== done =====" if execute else "===== dry run complete, nothing changed =====")
    return 0


if __name__ == "__main__":
    sys.exit(main())
